### ISSUE TITLE
Some teams are not being deleted, which causes the org to not be deleted

### ISSUE THREAD

**Issue by rhjhunt** [rhjhunt/ansible-examples#1]
##### SUMMARY

Some teams are not being deleted, which causes the org not to be deleted. There are no failures, it appears that the team is deleted based on the output, yet it still remains.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

_ansible-examples/delete_content/tower_delete_artifacts.yml_

##### EXPECTED RESULTS

For the team to be deleted and the org also.

##### ACTUAL RESULTS

The team appears to be deleted in the output, there are no failures yet the team is still in existence.

```yaml
{
    "ansible_loop_var": "team_item",
    "_ansible_no_log": false,
    "warnings": [
        "You are running collection version 3.8.6 but connecting to tower version 3.8.3"
    ],
    "changed": true,
    "invocation": {
        "module_args": {
            "new_name": null,
            "description": null,
            "tower_oauthtoken": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tower_host": "tower.example.com",
            "tower_username": "admin",
            "state": "absent",
            "tower_password": "",
            "tower_config_file": null,
            "organization": "PLAT_BUILD",
            "validate_certs": false,
            "name": "PLAT_BUILD_admins"
        }
    },
    "team_item": "PLAT_BUILD_admins",
    "id": 477,
    "_ansible_item_label": "PLAT_BUILD_admins"
}
```
